### ISSUE TITLE
getLocation regex erorr

### ISSUE THREAD

**Issue by matvejs16** [garrettjoecox/scriptserver#42]
Node script crashes when using server.rconConnection.util.getLocation(event.player)
![image](https://user-images.githubusercontent.com/74150728/147367474-9bbea916-3dd1-4e47-895a-78803c9088ab.png)

**Comment by matvejs16** [comment]
Same problem and same error with server.rconConnection.util.getEntityData()

**Comment by matvejs16** [comment]
Forgot, minecraft version: 1.12.2
Forge 1.12.2 Server

**Comment by garrettjoecox** [comment]
Well for one the node process shouldn’t crash from invalid regex, so I’ll need to debug and fix that one,

but I’m assuming the regex will also need to be altered from the default to accommodate for it being forge, I’ll try and respond with a fix tonight or tomorrow

**Comment by matvejs16** [comment]
The problem is with /data command, that command added to minecraft in 1.13 version

**Comment by garrettjoecox** [comment]
Ah right, there was a way to obtain xyz coords before 1.13, I’ll have to check the git history

**Comment by matvejs16** [comment]
Don't forget about server.rconConnection.util.getEntityData()
That uses /data command too

**Comment by iojanis** [comment]
I have somewhat the same problem with 1.18.2
Trying to get playerData aaaand... crash:

2022-04-27 13:29:13 error: uncaughtException: Cannot read properties of null (reading '2')
TypeError: Cannot read properties of null (reading '2')
    at Object.<anonymous> (/Users/j/Developer/Production/creaft3/node_modules/@scriptserver/util/src/useUtil.ts:72:89)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/janis/Developer/Production/creaft3/node_modules/@scriptserver/util/dist/useUtil.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
